// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDebS_EAaYQY9tyEhQ_vnartp6IMeWKD90',
    appId: '1:582970174780:web:03cc554861a9a62b2c8239',
    messagingSenderId: '582970174780',
    projectId: 'fasum-app-451f5',
    authDomain: 'fasum-app-451f5.firebaseapp.com',
    storageBucket: 'fasum-app-451f5.firebasestorage.app',
    measurementId: 'G-HVYY400B4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaT61eY-651PIk45CEm7bxeAG_x7Marhk',
    appId: '1:582970174780:android:35a669bf1684dda12c8239',
    messagingSenderId: '582970174780',
    projectId: 'fasum-app-451f5',
    storageBucket: 'fasum-app-451f5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDebS_EAaYQY9tyEhQ_vnartp6IMeWKD90',
    appId: '1:582970174780:web:9cbcf1f34cfa6bde2c8239',
    messagingSenderId: '582970174780',
    projectId: 'fasum-app-451f5',
    authDomain: 'fasum-app-451f5.firebaseapp.com',
    storageBucket: 'fasum-app-451f5.firebasestorage.app',
    measurementId: 'G-Y4X82RLG2X',
  );
}
